AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  cadastro-sneaker

  Sample SAM Template for cadastro-sneaker

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
    MemorySize: 256

  Api:
    TracingEnabled: true
    BinaryMediaTypes:
      - "multipart/form-data"
      - "application/json"
Resources:
  CadastrarSneakerFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: hello_world/
      Handler: app.lambda_handler
      Runtime: python3.12
      Architectures:
        - x86_64
      Events:
        CadastrarSneaker:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /sneakers
            Method: post

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  CadastrarSneakerApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  CadastrarSneakerFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt CadastrarSneakerFunction.Arn
  CadastrarSneakerFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt CadastrarSneakerFunctionRole.Arn
